// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/g-villarinho/oidc-server/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewAuthorizationCodeRepositoryMock creates a new instance of AuthorizationCodeRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthorizationCodeRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthorizationCodeRepositoryMock {
	mock := &AuthorizationCodeRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthorizationCodeRepositoryMock is an autogenerated mock type for the AuthorizationCodeRepository type
type AuthorizationCodeRepositoryMock struct {
	mock.Mock
}

type AuthorizationCodeRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthorizationCodeRepositoryMock) EXPECT() *AuthorizationCodeRepositoryMock_Expecter {
	return &AuthorizationCodeRepositoryMock_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type AuthorizationCodeRepositoryMock
func (_mock *AuthorizationCodeRepositoryMock) Create(ctx context.Context, code *domain.AuthorizationCode) error {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuthorizationCode) error); ok {
		r0 = returnFunc(ctx, code)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthorizationCodeRepositoryMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type AuthorizationCodeRepositoryMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - code *domain.AuthorizationCode
func (_e *AuthorizationCodeRepositoryMock_Expecter) Create(ctx interface{}, code interface{}) *AuthorizationCodeRepositoryMock_Create_Call {
	return &AuthorizationCodeRepositoryMock_Create_Call{Call: _e.mock.On("Create", ctx, code)}
}

func (_c *AuthorizationCodeRepositoryMock_Create_Call) Run(run func(ctx context.Context, code *domain.AuthorizationCode)) *AuthorizationCodeRepositoryMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuthorizationCode
		if args[1] != nil {
			arg1 = args[1].(*domain.AuthorizationCode)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthorizationCodeRepositoryMock_Create_Call) Return(err error) *AuthorizationCodeRepositoryMock_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthorizationCodeRepositoryMock_Create_Call) RunAndReturn(run func(ctx context.Context, code *domain.AuthorizationCode) error) *AuthorizationCodeRepositoryMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type AuthorizationCodeRepositoryMock
func (_mock *AuthorizationCodeRepositoryMock) Delete(ctx context.Context, code string) error {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, code)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthorizationCodeRepositoryMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type AuthorizationCodeRepositoryMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *AuthorizationCodeRepositoryMock_Expecter) Delete(ctx interface{}, code interface{}) *AuthorizationCodeRepositoryMock_Delete_Call {
	return &AuthorizationCodeRepositoryMock_Delete_Call{Call: _e.mock.On("Delete", ctx, code)}
}

func (_c *AuthorizationCodeRepositoryMock_Delete_Call) Run(run func(ctx context.Context, code string)) *AuthorizationCodeRepositoryMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthorizationCodeRepositoryMock_Delete_Call) Return(err error) *AuthorizationCodeRepositoryMock_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthorizationCodeRepositoryMock_Delete_Call) RunAndReturn(run func(ctx context.Context, code string) error) *AuthorizationCodeRepositoryMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCode provides a mock function for the type AuthorizationCodeRepositoryMock
func (_mock *AuthorizationCodeRepositoryMock) GetByCode(ctx context.Context, code string) (*domain.AuthorizationCode, error) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetByCode")
	}

	var r0 *domain.AuthorizationCode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.AuthorizationCode, error)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.AuthorizationCode); ok {
		r0 = returnFunc(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.AuthorizationCode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthorizationCodeRepositoryMock_GetByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCode'
type AuthorizationCodeRepositoryMock_GetByCode_Call struct {
	*mock.Call
}

// GetByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
func (_e *AuthorizationCodeRepositoryMock_Expecter) GetByCode(ctx interface{}, code interface{}) *AuthorizationCodeRepositoryMock_GetByCode_Call {
	return &AuthorizationCodeRepositoryMock_GetByCode_Call{Call: _e.mock.On("GetByCode", ctx, code)}
}

func (_c *AuthorizationCodeRepositoryMock_GetByCode_Call) Run(run func(ctx context.Context, code string)) *AuthorizationCodeRepositoryMock_GetByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthorizationCodeRepositoryMock_GetByCode_Call) Return(authorizationCode *domain.AuthorizationCode, err error) *AuthorizationCodeRepositoryMock_GetByCode_Call {
	_c.Call.Return(authorizationCode, err)
	return _c
}

func (_c *AuthorizationCodeRepositoryMock_GetByCode_Call) RunAndReturn(run func(ctx context.Context, code string) (*domain.AuthorizationCode, error)) *AuthorizationCodeRepositoryMock_GetByCode_Call {
	_c.Call.Return(run)
	return _c
}
