// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/g-villarinho/oidc-server/internal/core/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewAuthServiceMock creates a new instance of AuthServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthServiceMock {
	mock := &AuthServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthServiceMock is an autogenerated mock type for the AuthService type
type AuthServiceMock struct {
	mock.Mock
}

type AuthServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthServiceMock) EXPECT() *AuthServiceMock_Expecter {
	return &AuthServiceMock_Expecter{mock: &_m.Mock}
}

// GetSessionUser provides a mock function for the type AuthServiceMock
func (_mock *AuthServiceMock) GetSessionUser(ctx context.Context, sessionID uuid.UUID) (*domain.User, error) {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetSessionUser")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.User, error)); ok {
		return returnFunc(ctx, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.User); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthServiceMock_GetSessionUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSessionUser'
type AuthServiceMock_GetSessionUser_Call struct {
	*mock.Call
}

// GetSessionUser is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
func (_e *AuthServiceMock_Expecter) GetSessionUser(ctx interface{}, sessionID interface{}) *AuthServiceMock_GetSessionUser_Call {
	return &AuthServiceMock_GetSessionUser_Call{Call: _e.mock.On("GetSessionUser", ctx, sessionID)}
}

func (_c *AuthServiceMock_GetSessionUser_Call) Run(run func(ctx context.Context, sessionID uuid.UUID)) *AuthServiceMock_GetSessionUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthServiceMock_GetSessionUser_Call) Return(user *domain.User, err error) *AuthServiceMock_GetSessionUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *AuthServiceMock_GetSessionUser_Call) RunAndReturn(run func(ctx context.Context, sessionID uuid.UUID) (*domain.User, error)) *AuthServiceMock_GetSessionUser_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function for the type AuthServiceMock
func (_mock *AuthServiceMock) Login(ctx context.Context, email string, password string) (*domain.Session, *domain.User, error) {
	ret := _mock.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *domain.Session
	var r1 *domain.User
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*domain.Session, *domain.User, error)); ok {
		return returnFunc(ctx, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *domain.Session); ok {
		r0 = returnFunc(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) *domain.User); ok {
		r1 = returnFunc(ctx, email, password)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = returnFunc(ctx, email, password)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// AuthServiceMock_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type AuthServiceMock_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *AuthServiceMock_Expecter) Login(ctx interface{}, email interface{}, password interface{}) *AuthServiceMock_Login_Call {
	return &AuthServiceMock_Login_Call{Call: _e.mock.On("Login", ctx, email, password)}
}

func (_c *AuthServiceMock_Login_Call) Run(run func(ctx context.Context, email string, password string)) *AuthServiceMock_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuthServiceMock_Login_Call) Return(session *domain.Session, user *domain.User, err error) *AuthServiceMock_Login_Call {
	_c.Call.Return(session, user, err)
	return _c
}

func (_c *AuthServiceMock_Login_Call) RunAndReturn(run func(ctx context.Context, email string, password string) (*domain.Session, *domain.User, error)) *AuthServiceMock_Login_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterUser provides a mock function for the type AuthServiceMock
func (_mock *AuthServiceMock) RegisterUser(ctx context.Context, name string, email string, password string) error {
	ret := _mock.Called(ctx, name, email, password)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, name, email, password)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthServiceMock_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type AuthServiceMock_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - email string
//   - password string
func (_e *AuthServiceMock_Expecter) RegisterUser(ctx interface{}, name interface{}, email interface{}, password interface{}) *AuthServiceMock_RegisterUser_Call {
	return &AuthServiceMock_RegisterUser_Call{Call: _e.mock.On("RegisterUser", ctx, name, email, password)}
}

func (_c *AuthServiceMock_RegisterUser_Call) Run(run func(ctx context.Context, name string, email string, password string)) *AuthServiceMock_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *AuthServiceMock_RegisterUser_Call) Return(err error) *AuthServiceMock_RegisterUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthServiceMock_RegisterUser_Call) RunAndReturn(run func(ctx context.Context, name string, email string, password string) error) *AuthServiceMock_RegisterUser_Call {
	_c.Call.Return(run)
	return _c
}
