// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/g-villarinho/oidc-server/internal/core/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewAuthorizationServiceMock creates a new instance of AuthorizationServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthorizationServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthorizationServiceMock {
	mock := &AuthorizationServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthorizationServiceMock is an autogenerated mock type for the AuthorizationService type
type AuthorizationServiceMock struct {
	mock.Mock
}

type AuthorizationServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthorizationServiceMock) EXPECT() *AuthorizationServiceMock_Expecter {
	return &AuthorizationServiceMock_Expecter{mock: &_m.Mock}
}

// Authorize provides a mock function for the type AuthorizationServiceMock
func (_mock *AuthorizationServiceMock) Authorize(ctx context.Context, userID uuid.UUID, client *domain.Client, params domain.AuthorizeParams) (string, error) {
	ret := _mock.Called(ctx, userID, client, params)

	if len(ret) == 0 {
		panic("no return value specified for Authorize")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.Client, domain.AuthorizeParams) (string, error)); ok {
		return returnFunc(ctx, userID, client, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.Client, domain.AuthorizeParams) string); ok {
		r0 = returnFunc(ctx, userID, client, params)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *domain.Client, domain.AuthorizeParams) error); ok {
		r1 = returnFunc(ctx, userID, client, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthorizationServiceMock_Authorize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authorize'
type AuthorizationServiceMock_Authorize_Call struct {
	*mock.Call
}

// Authorize is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - client *domain.Client
//   - params domain.AuthorizeParams
func (_e *AuthorizationServiceMock_Expecter) Authorize(ctx interface{}, userID interface{}, client interface{}, params interface{}) *AuthorizationServiceMock_Authorize_Call {
	return &AuthorizationServiceMock_Authorize_Call{Call: _e.mock.On("Authorize", ctx, userID, client, params)}
}

func (_c *AuthorizationServiceMock_Authorize_Call) Run(run func(ctx context.Context, userID uuid.UUID, client *domain.Client, params domain.AuthorizeParams)) *AuthorizationServiceMock_Authorize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *domain.Client
		if args[2] != nil {
			arg2 = args[2].(*domain.Client)
		}
		var arg3 domain.AuthorizeParams
		if args[3] != nil {
			arg3 = args[3].(domain.AuthorizeParams)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *AuthorizationServiceMock_Authorize_Call) Return(s string, err error) *AuthorizationServiceMock_Authorize_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *AuthorizationServiceMock_Authorize_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, client *domain.Client, params domain.AuthorizeParams) (string, error)) *AuthorizationServiceMock_Authorize_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAuthorizationClient provides a mock function for the type AuthorizationServiceMock
func (_mock *AuthorizationServiceMock) ValidateAuthorizationClient(ctx context.Context, params domain.AuthorizeParams) (*domain.Client, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAuthorizationClient")
	}

	var r0 *domain.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AuthorizeParams) (*domain.Client, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AuthorizeParams) *domain.Client); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.AuthorizeParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthorizationServiceMock_ValidateAuthorizationClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAuthorizationClient'
type AuthorizationServiceMock_ValidateAuthorizationClient_Call struct {
	*mock.Call
}

// ValidateAuthorizationClient is a helper method to define mock.On call
//   - ctx context.Context
//   - params domain.AuthorizeParams
func (_e *AuthorizationServiceMock_Expecter) ValidateAuthorizationClient(ctx interface{}, params interface{}) *AuthorizationServiceMock_ValidateAuthorizationClient_Call {
	return &AuthorizationServiceMock_ValidateAuthorizationClient_Call{Call: _e.mock.On("ValidateAuthorizationClient", ctx, params)}
}

func (_c *AuthorizationServiceMock_ValidateAuthorizationClient_Call) Run(run func(ctx context.Context, params domain.AuthorizeParams)) *AuthorizationServiceMock_ValidateAuthorizationClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.AuthorizeParams
		if args[1] != nil {
			arg1 = args[1].(domain.AuthorizeParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthorizationServiceMock_ValidateAuthorizationClient_Call) Return(client *domain.Client, err error) *AuthorizationServiceMock_ValidateAuthorizationClient_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *AuthorizationServiceMock_ValidateAuthorizationClient_Call) RunAndReturn(run func(ctx context.Context, params domain.AuthorizeParams) (*domain.Client, error)) *AuthorizationServiceMock_ValidateAuthorizationClient_Call {
	_c.Call.Return(run)
	return _c
}
