// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewCacheMock creates a new instance of CacheMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCacheMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CacheMock {
	mock := &CacheMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CacheMock is an autogenerated mock type for the Cache type
type CacheMock struct {
	mock.Mock
}

type CacheMock_Expecter struct {
	mock *mock.Mock
}

func (_m *CacheMock) EXPECT() *CacheMock_Expecter {
	return &CacheMock_Expecter{mock: &_m.Mock}
}

// Decrement provides a mock function for the type CacheMock
func (_mock *CacheMock) Decrement(ctx context.Context, key string) (int64, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Decrement")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CacheMock_Decrement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decrement'
type CacheMock_Decrement_Call struct {
	*mock.Call
}

// Decrement is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *CacheMock_Expecter) Decrement(ctx interface{}, key interface{}) *CacheMock_Decrement_Call {
	return &CacheMock_Decrement_Call{Call: _e.mock.On("Decrement", ctx, key)}
}

func (_c *CacheMock_Decrement_Call) Run(run func(ctx context.Context, key string)) *CacheMock_Decrement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CacheMock_Decrement_Call) Return(n int64, err error) *CacheMock_Decrement_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *CacheMock_Decrement_Call) RunAndReturn(run func(ctx context.Context, key string) (int64, error)) *CacheMock_Decrement_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type CacheMock
func (_mock *CacheMock) Delete(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CacheMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type CacheMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *CacheMock_Expecter) Delete(ctx interface{}, key interface{}) *CacheMock_Delete_Call {
	return &CacheMock_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *CacheMock_Delete_Call) Run(run func(ctx context.Context, key string)) *CacheMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CacheMock_Delete_Call) Return(err error) *CacheMock_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CacheMock_Delete_Call) RunAndReturn(run func(ctx context.Context, key string) error) *CacheMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type CacheMock
func (_mock *CacheMock) Exists(ctx context.Context, key string) (bool, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CacheMock_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type CacheMock_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *CacheMock_Expecter) Exists(ctx interface{}, key interface{}) *CacheMock_Exists_Call {
	return &CacheMock_Exists_Call{Call: _e.mock.On("Exists", ctx, key)}
}

func (_c *CacheMock_Exists_Call) Run(run func(ctx context.Context, key string)) *CacheMock_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CacheMock_Exists_Call) Return(b bool, err error) *CacheMock_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *CacheMock_Exists_Call) RunAndReturn(run func(ctx context.Context, key string) (bool, error)) *CacheMock_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Expire provides a mock function for the type CacheMock
func (_mock *CacheMock) Expire(ctx context.Context, key string, ttl time.Duration) error {
	ret := _mock.Called(ctx, key, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Expire")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, key, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CacheMock_Expire_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Expire'
type CacheMock_Expire_Call struct {
	*mock.Call
}

// Expire is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - ttl time.Duration
func (_e *CacheMock_Expecter) Expire(ctx interface{}, key interface{}, ttl interface{}) *CacheMock_Expire_Call {
	return &CacheMock_Expire_Call{Call: _e.mock.On("Expire", ctx, key, ttl)}
}

func (_c *CacheMock_Expire_Call) Run(run func(ctx context.Context, key string, ttl time.Duration)) *CacheMock_Expire_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CacheMock_Expire_Call) Return(err error) *CacheMock_Expire_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CacheMock_Expire_Call) RunAndReturn(run func(ctx context.Context, key string, ttl time.Duration) error) *CacheMock_Expire_Call {
	_c.Call.Return(run)
	return _c
}

// FlushAll provides a mock function for the type CacheMock
func (_mock *CacheMock) FlushAll(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FlushAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CacheMock_FlushAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FlushAll'
type CacheMock_FlushAll_Call struct {
	*mock.Call
}

// FlushAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *CacheMock_Expecter) FlushAll(ctx interface{}) *CacheMock_FlushAll_Call {
	return &CacheMock_FlushAll_Call{Call: _e.mock.On("FlushAll", ctx)}
}

func (_c *CacheMock_FlushAll_Call) Run(run func(ctx context.Context)) *CacheMock_FlushAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *CacheMock_FlushAll_Call) Return(err error) *CacheMock_FlushAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CacheMock_FlushAll_Call) RunAndReturn(run func(ctx context.Context) error) *CacheMock_FlushAll_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type CacheMock
func (_mock *CacheMock) Get(ctx context.Context, key string) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CacheMock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type CacheMock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *CacheMock_Expecter) Get(ctx interface{}, key interface{}) *CacheMock_Get_Call {
	return &CacheMock_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *CacheMock_Get_Call) Run(run func(ctx context.Context, key string)) *CacheMock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CacheMock_Get_Call) Return(s string, err error) *CacheMock_Get_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *CacheMock_Get_Call) RunAndReturn(run func(ctx context.Context, key string) (string, error)) *CacheMock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetDel provides a mock function for the type CacheMock
func (_mock *CacheMock) GetDel(ctx context.Context, key string) (string, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetDel")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CacheMock_GetDel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDel'
type CacheMock_GetDel_Call struct {
	*mock.Call
}

// GetDel is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *CacheMock_Expecter) GetDel(ctx interface{}, key interface{}) *CacheMock_GetDel_Call {
	return &CacheMock_GetDel_Call{Call: _e.mock.On("GetDel", ctx, key)}
}

func (_c *CacheMock_GetDel_Call) Run(run func(ctx context.Context, key string)) *CacheMock_GetDel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CacheMock_GetDel_Call) Return(s string, err error) *CacheMock_GetDel_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *CacheMock_GetDel_Call) RunAndReturn(run func(ctx context.Context, key string) (string, error)) *CacheMock_GetDel_Call {
	_c.Call.Return(run)
	return _c
}

// Increment provides a mock function for the type CacheMock
func (_mock *CacheMock) Increment(ctx context.Context, key string) (int64, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Increment")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CacheMock_Increment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Increment'
type CacheMock_Increment_Call struct {
	*mock.Call
}

// Increment is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *CacheMock_Expecter) Increment(ctx interface{}, key interface{}) *CacheMock_Increment_Call {
	return &CacheMock_Increment_Call{Call: _e.mock.On("Increment", ctx, key)}
}

func (_c *CacheMock_Increment_Call) Run(run func(ctx context.Context, key string)) *CacheMock_Increment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CacheMock_Increment_Call) Return(n int64, err error) *CacheMock_Increment_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *CacheMock_Increment_Call) RunAndReturn(run func(ctx context.Context, key string) (int64, error)) *CacheMock_Increment_Call {
	_c.Call.Return(run)
	return _c
}

// MGet provides a mock function for the type CacheMock
func (_mock *CacheMock) MGet(ctx context.Context, keys ...string) ([]string, error) {
	var tmpRet mock.Arguments
	if len(keys) > 0 {
		tmpRet = _mock.Called(ctx, keys)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for MGet")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) ([]string, error)); ok {
		return returnFunc(ctx, keys...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) []string); ok {
		r0 = returnFunc(ctx, keys...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...string) error); ok {
		r1 = returnFunc(ctx, keys...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CacheMock_MGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MGet'
type CacheMock_MGet_Call struct {
	*mock.Call
}

// MGet is a helper method to define mock.On call
//   - ctx context.Context
//   - keys ...string
func (_e *CacheMock_Expecter) MGet(ctx interface{}, keys ...interface{}) *CacheMock_MGet_Call {
	return &CacheMock_MGet_Call{Call: _e.mock.On("MGet",
		append([]interface{}{ctx}, keys...)...)}
}

func (_c *CacheMock_MGet_Call) Run(run func(ctx context.Context, keys ...string)) *CacheMock_MGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *CacheMock_MGet_Call) Return(strings []string, err error) *CacheMock_MGet_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *CacheMock_MGet_Call) RunAndReturn(run func(ctx context.Context, keys ...string) ([]string, error)) *CacheMock_MGet_Call {
	_c.Call.Return(run)
	return _c
}

// MSet provides a mock function for the type CacheMock
func (_mock *CacheMock) MSet(ctx context.Context, pairs map[string]string, ttl time.Duration) error {
	ret := _mock.Called(ctx, pairs, ttl)

	if len(ret) == 0 {
		panic("no return value specified for MSet")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, map[string]string, time.Duration) error); ok {
		r0 = returnFunc(ctx, pairs, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CacheMock_MSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MSet'
type CacheMock_MSet_Call struct {
	*mock.Call
}

// MSet is a helper method to define mock.On call
//   - ctx context.Context
//   - pairs map[string]string
//   - ttl time.Duration
func (_e *CacheMock_Expecter) MSet(ctx interface{}, pairs interface{}, ttl interface{}) *CacheMock_MSet_Call {
	return &CacheMock_MSet_Call{Call: _e.mock.On("MSet", ctx, pairs, ttl)}
}

func (_c *CacheMock_MSet_Call) Run(run func(ctx context.Context, pairs map[string]string, ttl time.Duration)) *CacheMock_MSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 map[string]string
		if args[1] != nil {
			arg1 = args[1].(map[string]string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *CacheMock_MSet_Call) Return(err error) *CacheMock_MSet_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CacheMock_MSet_Call) RunAndReturn(run func(ctx context.Context, pairs map[string]string, ttl time.Duration) error) *CacheMock_MSet_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type CacheMock
func (_mock *CacheMock) Set(ctx context.Context, key string, value string, ttl time.Duration) error {
	ret := _mock.Called(ctx, key, value, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, key, value, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CacheMock_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type CacheMock_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value string
//   - ttl time.Duration
func (_e *CacheMock_Expecter) Set(ctx interface{}, key interface{}, value interface{}, ttl interface{}) *CacheMock_Set_Call {
	return &CacheMock_Set_Call{Call: _e.mock.On("Set", ctx, key, value, ttl)}
}

func (_c *CacheMock_Set_Call) Run(run func(ctx context.Context, key string, value string, ttl time.Duration)) *CacheMock_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *CacheMock_Set_Call) Return(err error) *CacheMock_Set_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CacheMock_Set_Call) RunAndReturn(run func(ctx context.Context, key string, value string, ttl time.Duration) error) *CacheMock_Set_Call {
	_c.Call.Return(run)
	return _c
}

// SetNX provides a mock function for the type CacheMock
func (_mock *CacheMock) SetNX(ctx context.Context, key string, value string, ttl time.Duration) (bool, error) {
	ret := _mock.Called(ctx, key, value, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetNX")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) (bool, error)); ok {
		return returnFunc(ctx, key, value, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) bool); ok {
		r0 = returnFunc(ctx, key, value, ttl)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, time.Duration) error); ok {
		r1 = returnFunc(ctx, key, value, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CacheMock_SetNX_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNX'
type CacheMock_SetNX_Call struct {
	*mock.Call
}

// SetNX is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value string
//   - ttl time.Duration
func (_e *CacheMock_Expecter) SetNX(ctx interface{}, key interface{}, value interface{}, ttl interface{}) *CacheMock_SetNX_Call {
	return &CacheMock_SetNX_Call{Call: _e.mock.On("SetNX", ctx, key, value, ttl)}
}

func (_c *CacheMock_SetNX_Call) Run(run func(ctx context.Context, key string, value string, ttl time.Duration)) *CacheMock_SetNX_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *CacheMock_SetNX_Call) Return(b bool, err error) *CacheMock_SetNX_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *CacheMock_SetNX_Call) RunAndReturn(run func(ctx context.Context, key string, value string, ttl time.Duration) (bool, error)) *CacheMock_SetNX_Call {
	_c.Call.Return(run)
	return _c
}

// TTL provides a mock function for the type CacheMock
func (_mock *CacheMock) TTL(ctx context.Context, key string) (time.Duration, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for TTL")
	}

	var r0 time.Duration
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (time.Duration, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) time.Duration); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CacheMock_TTL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TTL'
type CacheMock_TTL_Call struct {
	*mock.Call
}

// TTL is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *CacheMock_Expecter) TTL(ctx interface{}, key interface{}) *CacheMock_TTL_Call {
	return &CacheMock_TTL_Call{Call: _e.mock.On("TTL", ctx, key)}
}

func (_c *CacheMock_TTL_Call) Run(run func(ctx context.Context, key string)) *CacheMock_TTL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CacheMock_TTL_Call) Return(duration time.Duration, err error) *CacheMock_TTL_Call {
	_c.Call.Return(duration, err)
	return _c
}

func (_c *CacheMock_TTL_Call) RunAndReturn(run func(ctx context.Context, key string) (time.Duration, error)) *CacheMock_TTL_Call {
	_c.Call.Return(run)
	return _c
}
