// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/g-villarinho/oidc-server/internal/core/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewClientRepositoryMock creates a new instance of ClientRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientRepositoryMock {
	mock := &ClientRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ClientRepositoryMock is an autogenerated mock type for the ClientRepository type
type ClientRepositoryMock struct {
	mock.Mock
}

type ClientRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientRepositoryMock) EXPECT() *ClientRepositoryMock_Expecter {
	return &ClientRepositoryMock_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type ClientRepositoryMock
func (_mock *ClientRepositoryMock) Create(ctx context.Context, client *domain.Client) error {
	ret := _mock.Called(ctx, client)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Client) error); ok {
		r0 = returnFunc(ctx, client)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ClientRepositoryMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ClientRepositoryMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - client *domain.Client
func (_e *ClientRepositoryMock_Expecter) Create(ctx interface{}, client interface{}) *ClientRepositoryMock_Create_Call {
	return &ClientRepositoryMock_Create_Call{Call: _e.mock.On("Create", ctx, client)}
}

func (_c *ClientRepositoryMock_Create_Call) Run(run func(ctx context.Context, client *domain.Client)) *ClientRepositoryMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Client
		if args[1] != nil {
			arg1 = args[1].(*domain.Client)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClientRepositoryMock_Create_Call) Return(err error) *ClientRepositoryMock_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ClientRepositoryMock_Create_Call) RunAndReturn(run func(ctx context.Context, client *domain.Client) error) *ClientRepositoryMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type ClientRepositoryMock
func (_mock *ClientRepositoryMock) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ClientRepositoryMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ClientRepositoryMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ClientRepositoryMock_Expecter) Delete(ctx interface{}, id interface{}) *ClientRepositoryMock_Delete_Call {
	return &ClientRepositoryMock_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *ClientRepositoryMock_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ClientRepositoryMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClientRepositoryMock_Delete_Call) Return(err error) *ClientRepositoryMock_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ClientRepositoryMock_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *ClientRepositoryMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByClientID provides a mock function for the type ClientRepositoryMock
func (_mock *ClientRepositoryMock) GetByClientID(ctx context.Context, clientID string) (*domain.Client, error) {
	ret := _mock.Called(ctx, clientID)

	if len(ret) == 0 {
		panic("no return value specified for GetByClientID")
	}

	var r0 *domain.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Client, error)); ok {
		return returnFunc(ctx, clientID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Client); ok {
		r0 = returnFunc(ctx, clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, clientID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClientRepositoryMock_GetByClientID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByClientID'
type ClientRepositoryMock_GetByClientID_Call struct {
	*mock.Call
}

// GetByClientID is a helper method to define mock.On call
//   - ctx context.Context
//   - clientID string
func (_e *ClientRepositoryMock_Expecter) GetByClientID(ctx interface{}, clientID interface{}) *ClientRepositoryMock_GetByClientID_Call {
	return &ClientRepositoryMock_GetByClientID_Call{Call: _e.mock.On("GetByClientID", ctx, clientID)}
}

func (_c *ClientRepositoryMock_GetByClientID_Call) Run(run func(ctx context.Context, clientID string)) *ClientRepositoryMock_GetByClientID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClientRepositoryMock_GetByClientID_Call) Return(client *domain.Client, err error) *ClientRepositoryMock_GetByClientID_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *ClientRepositoryMock_GetByClientID_Call) RunAndReturn(run func(ctx context.Context, clientID string) (*domain.Client, error)) *ClientRepositoryMock_GetByClientID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type ClientRepositoryMock
func (_mock *ClientRepositoryMock) GetByID(ctx context.Context, id uuid.UUID) (*domain.Client, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Client, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Client); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClientRepositoryMock_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type ClientRepositoryMock_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ClientRepositoryMock_Expecter) GetByID(ctx interface{}, id interface{}) *ClientRepositoryMock_GetByID_Call {
	return &ClientRepositoryMock_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *ClientRepositoryMock_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ClientRepositoryMock_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClientRepositoryMock_GetByID_Call) Return(client *domain.Client, err error) *ClientRepositoryMock_GetByID_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *ClientRepositoryMock_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*domain.Client, error)) *ClientRepositoryMock_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type ClientRepositoryMock
func (_mock *ClientRepositoryMock) List(ctx context.Context) ([]*domain.Client, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*domain.Client, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*domain.Client); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClientRepositoryMock_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ClientRepositoryMock_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ClientRepositoryMock_Expecter) List(ctx interface{}) *ClientRepositoryMock_List_Call {
	return &ClientRepositoryMock_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *ClientRepositoryMock_List_Call) Run(run func(ctx context.Context)) *ClientRepositoryMock_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ClientRepositoryMock_List_Call) Return(clients []*domain.Client, err error) *ClientRepositoryMock_List_Call {
	_c.Call.Return(clients, err)
	return _c
}

func (_c *ClientRepositoryMock_List_Call) RunAndReturn(run func(ctx context.Context) ([]*domain.Client, error)) *ClientRepositoryMock_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type ClientRepositoryMock
func (_mock *ClientRepositoryMock) Update(ctx context.Context, client *domain.Client) error {
	ret := _mock.Called(ctx, client)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Client) error); ok {
		r0 = returnFunc(ctx, client)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ClientRepositoryMock_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type ClientRepositoryMock_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - client *domain.Client
func (_e *ClientRepositoryMock_Expecter) Update(ctx interface{}, client interface{}) *ClientRepositoryMock_Update_Call {
	return &ClientRepositoryMock_Update_Call{Call: _e.mock.On("Update", ctx, client)}
}

func (_c *ClientRepositoryMock_Update_Call) Run(run func(ctx context.Context, client *domain.Client)) *ClientRepositoryMock_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Client
		if args[1] != nil {
			arg1 = args[1].(*domain.Client)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClientRepositoryMock_Update_Call) Return(err error) *ClientRepositoryMock_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ClientRepositoryMock_Update_Call) RunAndReturn(run func(ctx context.Context, client *domain.Client) error) *ClientRepositoryMock_Update_Call {
	_c.Call.Return(run)
	return _c
}
