// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/g-villarinho/oidc-server/internal/core/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewClientServiceMock creates a new instance of ClientServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientServiceMock {
	mock := &ClientServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ClientServiceMock is an autogenerated mock type for the ClientService type
type ClientServiceMock struct {
	mock.Mock
}

type ClientServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ClientServiceMock) EXPECT() *ClientServiceMock_Expecter {
	return &ClientServiceMock_Expecter{mock: &_m.Mock}
}

// CreateClient provides a mock function for the type ClientServiceMock
func (_mock *ClientServiceMock) CreateClient(ctx context.Context, params domain.CreateClientParams) (*domain.Client, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateClient")
	}

	var r0 *domain.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.CreateClientParams) (*domain.Client, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.CreateClientParams) *domain.Client); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.CreateClientParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClientServiceMock_CreateClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateClient'
type ClientServiceMock_CreateClient_Call struct {
	*mock.Call
}

// CreateClient is a helper method to define mock.On call
//   - ctx context.Context
//   - params domain.CreateClientParams
func (_e *ClientServiceMock_Expecter) CreateClient(ctx interface{}, params interface{}) *ClientServiceMock_CreateClient_Call {
	return &ClientServiceMock_CreateClient_Call{Call: _e.mock.On("CreateClient", ctx, params)}
}

func (_c *ClientServiceMock_CreateClient_Call) Run(run func(ctx context.Context, params domain.CreateClientParams)) *ClientServiceMock_CreateClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.CreateClientParams
		if args[1] != nil {
			arg1 = args[1].(domain.CreateClientParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClientServiceMock_CreateClient_Call) Return(client *domain.Client, err error) *ClientServiceMock_CreateClient_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *ClientServiceMock_CreateClient_Call) RunAndReturn(run func(ctx context.Context, params domain.CreateClientParams) (*domain.Client, error)) *ClientServiceMock_CreateClient_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteClient provides a mock function for the type ClientServiceMock
func (_mock *ClientServiceMock) DeleteClient(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteClient")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ClientServiceMock_DeleteClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteClient'
type ClientServiceMock_DeleteClient_Call struct {
	*mock.Call
}

// DeleteClient is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ClientServiceMock_Expecter) DeleteClient(ctx interface{}, id interface{}) *ClientServiceMock_DeleteClient_Call {
	return &ClientServiceMock_DeleteClient_Call{Call: _e.mock.On("DeleteClient", ctx, id)}
}

func (_c *ClientServiceMock_DeleteClient_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ClientServiceMock_DeleteClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClientServiceMock_DeleteClient_Call) Return(err error) *ClientServiceMock_DeleteClient_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ClientServiceMock_DeleteClient_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *ClientServiceMock_DeleteClient_Call {
	_c.Call.Return(run)
	return _c
}

// GetClientByID provides a mock function for the type ClientServiceMock
func (_mock *ClientServiceMock) GetClientByID(ctx context.Context, id uuid.UUID) (*domain.Client, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetClientByID")
	}

	var r0 *domain.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Client, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Client); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClientServiceMock_GetClientByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClientByID'
type ClientServiceMock_GetClientByID_Call struct {
	*mock.Call
}

// GetClientByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *ClientServiceMock_Expecter) GetClientByID(ctx interface{}, id interface{}) *ClientServiceMock_GetClientByID_Call {
	return &ClientServiceMock_GetClientByID_Call{Call: _e.mock.On("GetClientByID", ctx, id)}
}

func (_c *ClientServiceMock_GetClientByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *ClientServiceMock_GetClientByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *ClientServiceMock_GetClientByID_Call) Return(client *domain.Client, err error) *ClientServiceMock_GetClientByID_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *ClientServiceMock_GetClientByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*domain.Client, error)) *ClientServiceMock_GetClientByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListClients provides a mock function for the type ClientServiceMock
func (_mock *ClientServiceMock) ListClients(ctx context.Context) ([]*domain.Client, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListClients")
	}

	var r0 []*domain.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*domain.Client, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*domain.Client); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClientServiceMock_ListClients_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListClients'
type ClientServiceMock_ListClients_Call struct {
	*mock.Call
}

// ListClients is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ClientServiceMock_Expecter) ListClients(ctx interface{}) *ClientServiceMock_ListClients_Call {
	return &ClientServiceMock_ListClients_Call{Call: _e.mock.On("ListClients", ctx)}
}

func (_c *ClientServiceMock_ListClients_Call) Run(run func(ctx context.Context)) *ClientServiceMock_ListClients_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ClientServiceMock_ListClients_Call) Return(clients []*domain.Client, err error) *ClientServiceMock_ListClients_Call {
	_c.Call.Return(clients, err)
	return _c
}

func (_c *ClientServiceMock_ListClients_Call) RunAndReturn(run func(ctx context.Context) ([]*domain.Client, error)) *ClientServiceMock_ListClients_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateClient provides a mock function for the type ClientServiceMock
func (_mock *ClientServiceMock) UpdateClient(ctx context.Context, id uuid.UUID, clientName string, redirectURIs []string, grantTypes []string, responseTypes []string, scopes []string) (*domain.Client, error) {
	ret := _mock.Called(ctx, id, clientName, redirectURIs, grantTypes, responseTypes, scopes)

	if len(ret) == 0 {
		panic("no return value specified for UpdateClient")
	}

	var r0 *domain.Client
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, []string, []string, []string, []string) (*domain.Client, error)); ok {
		return returnFunc(ctx, id, clientName, redirectURIs, grantTypes, responseTypes, scopes)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, []string, []string, []string, []string) *domain.Client); ok {
		r0 = returnFunc(ctx, id, clientName, redirectURIs, grantTypes, responseTypes, scopes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Client)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, []string, []string, []string, []string) error); ok {
		r1 = returnFunc(ctx, id, clientName, redirectURIs, grantTypes, responseTypes, scopes)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ClientServiceMock_UpdateClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateClient'
type ClientServiceMock_UpdateClient_Call struct {
	*mock.Call
}

// UpdateClient is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - clientName string
//   - redirectURIs []string
//   - grantTypes []string
//   - responseTypes []string
//   - scopes []string
func (_e *ClientServiceMock_Expecter) UpdateClient(ctx interface{}, id interface{}, clientName interface{}, redirectURIs interface{}, grantTypes interface{}, responseTypes interface{}, scopes interface{}) *ClientServiceMock_UpdateClient_Call {
	return &ClientServiceMock_UpdateClient_Call{Call: _e.mock.On("UpdateClient", ctx, id, clientName, redirectURIs, grantTypes, responseTypes, scopes)}
}

func (_c *ClientServiceMock_UpdateClient_Call) Run(run func(ctx context.Context, id uuid.UUID, clientName string, redirectURIs []string, grantTypes []string, responseTypes []string, scopes []string)) *ClientServiceMock_UpdateClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []string
		if args[3] != nil {
			arg3 = args[3].([]string)
		}
		var arg4 []string
		if args[4] != nil {
			arg4 = args[4].([]string)
		}
		var arg5 []string
		if args[5] != nil {
			arg5 = args[5].([]string)
		}
		var arg6 []string
		if args[6] != nil {
			arg6 = args[6].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *ClientServiceMock_UpdateClient_Call) Return(client *domain.Client, err error) *ClientServiceMock_UpdateClient_Call {
	_c.Call.Return(client, err)
	return _c
}

func (_c *ClientServiceMock_UpdateClient_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, clientName string, redirectURIs []string, grantTypes []string, responseTypes []string, scopes []string) (*domain.Client, error)) *ClientServiceMock_UpdateClient_Call {
	_c.Call.Return(run)
	return _c
}
