// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewHasherMock creates a new instance of HasherMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHasherMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *HasherMock {
	mock := &HasherMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// HasherMock is an autogenerated mock type for the Hasher type
type HasherMock struct {
	mock.Mock
}

type HasherMock_Expecter struct {
	mock *mock.Mock
}

func (_m *HasherMock) EXPECT() *HasherMock_Expecter {
	return &HasherMock_Expecter{mock: &_m.Mock}
}

// Compare provides a mock function for the type HasherMock
func (_mock *HasherMock) Compare(ctx context.Context, plaintext string, hashed string) error {
	ret := _mock.Called(ctx, plaintext, hashed)

	if len(ret) == 0 {
		panic("no return value specified for Compare")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, plaintext, hashed)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// HasherMock_Compare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Compare'
type HasherMock_Compare_Call struct {
	*mock.Call
}

// Compare is a helper method to define mock.On call
//   - ctx context.Context
//   - plaintext string
//   - hashed string
func (_e *HasherMock_Expecter) Compare(ctx interface{}, plaintext interface{}, hashed interface{}) *HasherMock_Compare_Call {
	return &HasherMock_Compare_Call{Call: _e.mock.On("Compare", ctx, plaintext, hashed)}
}

func (_c *HasherMock_Compare_Call) Run(run func(ctx context.Context, plaintext string, hashed string)) *HasherMock_Compare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *HasherMock_Compare_Call) Return(err error) *HasherMock_Compare_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *HasherMock_Compare_Call) RunAndReturn(run func(ctx context.Context, plaintext string, hashed string) error) *HasherMock_Compare_Call {
	_c.Call.Return(run)
	return _c
}

// Hash provides a mock function for the type HasherMock
func (_mock *HasherMock) Hash(ctx context.Context, plaintext string) (string, error) {
	ret := _mock.Called(ctx, plaintext)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, plaintext)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, plaintext)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, plaintext)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// HasherMock_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type HasherMock_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - ctx context.Context
//   - plaintext string
func (_e *HasherMock_Expecter) Hash(ctx interface{}, plaintext interface{}) *HasherMock_Hash_Call {
	return &HasherMock_Hash_Call{Call: _e.mock.On("Hash", ctx, plaintext)}
}

func (_c *HasherMock_Hash_Call) Run(run func(ctx context.Context, plaintext string)) *HasherMock_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *HasherMock_Hash_Call) Return(s string, err error) *HasherMock_Hash_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *HasherMock_Hash_Call) RunAndReturn(run func(ctx context.Context, plaintext string) (string, error)) *HasherMock_Hash_Call {
	_c.Call.Return(run)
	return _c
}
