// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/g-villarinho/oidc-server/internal/core/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewSessionRepositoryMock creates a new instance of SessionRepositoryMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionRepositoryMock {
	mock := &SessionRepositoryMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SessionRepositoryMock is an autogenerated mock type for the SessionRepository type
type SessionRepositoryMock struct {
	mock.Mock
}

type SessionRepositoryMock_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionRepositoryMock) EXPECT() *SessionRepositoryMock_Expecter {
	return &SessionRepositoryMock_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type SessionRepositoryMock
func (_mock *SessionRepositoryMock) Create(ctx context.Context, session *domain.Session) error {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Session) error); ok {
		r0 = returnFunc(ctx, session)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRepositoryMock_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type SessionRepositoryMock_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - session *domain.Session
func (_e *SessionRepositoryMock_Expecter) Create(ctx interface{}, session interface{}) *SessionRepositoryMock_Create_Call {
	return &SessionRepositoryMock_Create_Call{Call: _e.mock.On("Create", ctx, session)}
}

func (_c *SessionRepositoryMock_Create_Call) Run(run func(ctx context.Context, session *domain.Session)) *SessionRepositoryMock_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Session
		if args[1] != nil {
			arg1 = args[1].(*domain.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepositoryMock_Create_Call) Return(err error) *SessionRepositoryMock_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRepositoryMock_Create_Call) RunAndReturn(run func(ctx context.Context, session *domain.Session) error) *SessionRepositoryMock_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type SessionRepositoryMock
func (_mock *SessionRepositoryMock) Delete(ctx context.Context, sessionID uuid.UUID) error {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRepositoryMock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type SessionRepositoryMock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
func (_e *SessionRepositoryMock_Expecter) Delete(ctx interface{}, sessionID interface{}) *SessionRepositoryMock_Delete_Call {
	return &SessionRepositoryMock_Delete_Call{Call: _e.mock.On("Delete", ctx, sessionID)}
}

func (_c *SessionRepositoryMock_Delete_Call) Run(run func(ctx context.Context, sessionID uuid.UUID)) *SessionRepositoryMock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepositoryMock_Delete_Call) Return(err error) *SessionRepositoryMock_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRepositoryMock_Delete_Call) RunAndReturn(run func(ctx context.Context, sessionID uuid.UUID) error) *SessionRepositoryMock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type SessionRepositoryMock
func (_mock *SessionRepositoryMock) GetByID(ctx context.Context, sessionID uuid.UUID) (*domain.Session, error) {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Session, error)); ok {
		return returnFunc(ctx, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Session); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionRepositoryMock_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type SessionRepositoryMock_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
func (_e *SessionRepositoryMock_Expecter) GetByID(ctx interface{}, sessionID interface{}) *SessionRepositoryMock_GetByID_Call {
	return &SessionRepositoryMock_GetByID_Call{Call: _e.mock.On("GetByID", ctx, sessionID)}
}

func (_c *SessionRepositoryMock_GetByID_Call) Run(run func(ctx context.Context, sessionID uuid.UUID)) *SessionRepositoryMock_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepositoryMock_GetByID_Call) Return(session *domain.Session, err error) *SessionRepositoryMock_GetByID_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *SessionRepositoryMock_GetByID_Call) RunAndReturn(run func(ctx context.Context, sessionID uuid.UUID) (*domain.Session, error)) *SessionRepositoryMock_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function for the type SessionRepositoryMock
func (_mock *SessionRepositoryMock) GetByUserID(ctx context.Context, userID uuid.UUID) ([]*domain.Session, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []*domain.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*domain.Session, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*domain.Session); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionRepositoryMock_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type SessionRepositoryMock_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *SessionRepositoryMock_Expecter) GetByUserID(ctx interface{}, userID interface{}) *SessionRepositoryMock_GetByUserID_Call {
	return &SessionRepositoryMock_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *SessionRepositoryMock_GetByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *SessionRepositoryMock_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRepositoryMock_GetByUserID_Call) Return(sessions []*domain.Session, err error) *SessionRepositoryMock_GetByUserID_Call {
	_c.Call.Return(sessions, err)
	return _c
}

func (_c *SessionRepositoryMock_GetByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]*domain.Session, error)) *SessionRepositoryMock_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}
