// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/g-villarinho/oidc-server/internal/core/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewTokenGeneratorMock creates a new instance of TokenGeneratorMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenGeneratorMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenGeneratorMock {
	mock := &TokenGeneratorMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TokenGeneratorMock is an autogenerated mock type for the TokenGenerator type
type TokenGeneratorMock struct {
	mock.Mock
}

type TokenGeneratorMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenGeneratorMock) EXPECT() *TokenGeneratorMock_Expecter {
	return &TokenGeneratorMock_Expecter{mock: &_m.Mock}
}

// GenerateAccessToken provides a mock function for the type TokenGeneratorMock
func (_mock *TokenGeneratorMock) GenerateAccessToken(ctx context.Context, userID uuid.UUID, client *domain.Client, ttl time.Duration) (string, error) {
	ret := _mock.Called(ctx, userID, client, ttl)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccessToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.Client, time.Duration) (string, error)); ok {
		return returnFunc(ctx, userID, client, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, *domain.Client, time.Duration) string); ok {
		r0 = returnFunc(ctx, userID, client, ttl)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, *domain.Client, time.Duration) error); ok {
		r1 = returnFunc(ctx, userID, client, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenGeneratorMock_GenerateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAccessToken'
type TokenGeneratorMock_GenerateAccessToken_Call struct {
	*mock.Call
}

// GenerateAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - client *domain.Client
//   - ttl time.Duration
func (_e *TokenGeneratorMock_Expecter) GenerateAccessToken(ctx interface{}, userID interface{}, client interface{}, ttl interface{}) *TokenGeneratorMock_GenerateAccessToken_Call {
	return &TokenGeneratorMock_GenerateAccessToken_Call{Call: _e.mock.On("GenerateAccessToken", ctx, userID, client, ttl)}
}

func (_c *TokenGeneratorMock_GenerateAccessToken_Call) Run(run func(ctx context.Context, userID uuid.UUID, client *domain.Client, ttl time.Duration)) *TokenGeneratorMock_GenerateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 *domain.Client
		if args[2] != nil {
			arg2 = args[2].(*domain.Client)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *TokenGeneratorMock_GenerateAccessToken_Call) Return(s string, err error) *TokenGeneratorMock_GenerateAccessToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *TokenGeneratorMock_GenerateAccessToken_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, client *domain.Client, ttl time.Duration) (string, error)) *TokenGeneratorMock_GenerateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateIDToken provides a mock function for the type TokenGeneratorMock
func (_mock *TokenGeneratorMock) GenerateIDToken(ctx context.Context, user *domain.User, client *domain.Client, nonce string, ttl time.Duration) (string, error) {
	ret := _mock.Called(ctx, user, client, nonce, ttl)

	if len(ret) == 0 {
		panic("no return value specified for GenerateIDToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.User, *domain.Client, string, time.Duration) (string, error)); ok {
		return returnFunc(ctx, user, client, nonce, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.User, *domain.Client, string, time.Duration) string); ok {
		r0 = returnFunc(ctx, user, client, nonce, ttl)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.User, *domain.Client, string, time.Duration) error); ok {
		r1 = returnFunc(ctx, user, client, nonce, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenGeneratorMock_GenerateIDToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateIDToken'
type TokenGeneratorMock_GenerateIDToken_Call struct {
	*mock.Call
}

// GenerateIDToken is a helper method to define mock.On call
//   - ctx context.Context
//   - user *domain.User
//   - client *domain.Client
//   - nonce string
//   - ttl time.Duration
func (_e *TokenGeneratorMock_Expecter) GenerateIDToken(ctx interface{}, user interface{}, client interface{}, nonce interface{}, ttl interface{}) *TokenGeneratorMock_GenerateIDToken_Call {
	return &TokenGeneratorMock_GenerateIDToken_Call{Call: _e.mock.On("GenerateIDToken", ctx, user, client, nonce, ttl)}
}

func (_c *TokenGeneratorMock_GenerateIDToken_Call) Run(run func(ctx context.Context, user *domain.User, client *domain.Client, nonce string, ttl time.Duration)) *TokenGeneratorMock_GenerateIDToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.User
		if args[1] != nil {
			arg1 = args[1].(*domain.User)
		}
		var arg2 *domain.Client
		if args[2] != nil {
			arg2 = args[2].(*domain.Client)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 time.Duration
		if args[4] != nil {
			arg4 = args[4].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *TokenGeneratorMock_GenerateIDToken_Call) Return(s string, err error) *TokenGeneratorMock_GenerateIDToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *TokenGeneratorMock_GenerateIDToken_Call) RunAndReturn(run func(ctx context.Context, user *domain.User, client *domain.Client, nonce string, ttl time.Duration) (string, error)) *TokenGeneratorMock_GenerateIDToken_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateRefreshToken provides a mock function for the type TokenGeneratorMock
func (_mock *TokenGeneratorMock) GenerateRefreshToken(ctx context.Context) (string, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GenerateRefreshToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenGeneratorMock_GenerateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRefreshToken'
type TokenGeneratorMock_GenerateRefreshToken_Call struct {
	*mock.Call
}

// GenerateRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
func (_e *TokenGeneratorMock_Expecter) GenerateRefreshToken(ctx interface{}) *TokenGeneratorMock_GenerateRefreshToken_Call {
	return &TokenGeneratorMock_GenerateRefreshToken_Call{Call: _e.mock.On("GenerateRefreshToken", ctx)}
}

func (_c *TokenGeneratorMock_GenerateRefreshToken_Call) Run(run func(ctx context.Context)) *TokenGeneratorMock_GenerateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TokenGeneratorMock_GenerateRefreshToken_Call) Return(s string, err error) *TokenGeneratorMock_GenerateRefreshToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *TokenGeneratorMock_GenerateRefreshToken_Call) RunAndReturn(run func(ctx context.Context) (string, error)) *TokenGeneratorMock_GenerateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}
