// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/g-villarinho/oidc-server/internal/core/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewUserServiceMock creates a new instance of UserServiceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserServiceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserServiceMock {
	mock := &UserServiceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserServiceMock is an autogenerated mock type for the UserService type
type UserServiceMock struct {
	mock.Mock
}

type UserServiceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *UserServiceMock) EXPECT() *UserServiceMock_Expecter {
	return &UserServiceMock_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type UserServiceMock
func (_mock *UserServiceMock) Authenticate(ctx context.Context, email string, password string) (*domain.User, error) {
	ret := _mock.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*domain.User, error)); ok {
		return returnFunc(ctx, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *domain.User); ok {
		r0 = returnFunc(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserServiceMock_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type UserServiceMock_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *UserServiceMock_Expecter) Authenticate(ctx interface{}, email interface{}, password interface{}) *UserServiceMock_Authenticate_Call {
	return &UserServiceMock_Authenticate_Call{Call: _e.mock.On("Authenticate", ctx, email, password)}
}

func (_c *UserServiceMock_Authenticate_Call) Run(run func(ctx context.Context, email string, password string)) *UserServiceMock_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserServiceMock_Authenticate_Call) Return(user *domain.User, err error) *UserServiceMock_Authenticate_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserServiceMock_Authenticate_Call) RunAndReturn(run func(ctx context.Context, email string, password string) (*domain.User, error)) *UserServiceMock_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function for the type UserServiceMock
func (_mock *UserServiceMock) CreateUser(ctx context.Context, name string, email string, password string) (*domain.User, error) {
	ret := _mock.Called(ctx, name, email, password)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*domain.User, error)); ok {
		return returnFunc(ctx, name, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *domain.User); ok {
		r0 = returnFunc(ctx, name, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, name, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserServiceMock_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type UserServiceMock_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - email string
//   - password string
func (_e *UserServiceMock_Expecter) CreateUser(ctx interface{}, name interface{}, email interface{}, password interface{}) *UserServiceMock_CreateUser_Call {
	return &UserServiceMock_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, name, email, password)}
}

func (_c *UserServiceMock_CreateUser_Call) Run(run func(ctx context.Context, name string, email string, password string)) *UserServiceMock_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *UserServiceMock_CreateUser_Call) Return(user *domain.User, err error) *UserServiceMock_CreateUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserServiceMock_CreateUser_Call) RunAndReturn(run func(ctx context.Context, name string, email string, password string) (*domain.User, error)) *UserServiceMock_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type UserServiceMock
func (_mock *UserServiceMock) GetUserByID(ctx context.Context, userID uuid.UUID) (*domain.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserServiceMock_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type UserServiceMock_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *UserServiceMock_Expecter) GetUserByID(ctx interface{}, userID interface{}) *UserServiceMock_GetUserByID_Call {
	return &UserServiceMock_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, userID)}
}

func (_c *UserServiceMock_GetUserByID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *UserServiceMock_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserServiceMock_GetUserByID_Call) Return(user *domain.User, err error) *UserServiceMock_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserServiceMock_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (*domain.User, error)) *UserServiceMock_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}
