// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClient = `-- name: CreateClient :one
INSERT INTO oauth_clients (
    id,
    client_id,
    client_secret,
    client_name,
    redirect_uris,
    grant_types,
    response_types,
    scope,
    logo_url
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, client_id, client_secret, client_name, redirect_uris, grant_types, response_types, scope, logo_url, created_at, updated_at
`

type CreateClientParams struct {
	ID            pgtype.UUID `json:"id"`
	ClientID      string      `json:"client_id"`
	ClientSecret  string      `json:"client_secret"`
	ClientName    string      `json:"client_name"`
	RedirectUris  []string    `json:"redirect_uris"`
	GrantTypes    []string    `json:"grant_types"`
	ResponseTypes []string    `json:"response_types"`
	Scope         string      `json:"scope"`
	LogoUrl       string      `json:"logo_url"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (OauthClient, error) {
	row := q.db.QueryRow(ctx, createClient,
		arg.ID,
		arg.ClientID,
		arg.ClientSecret,
		arg.ClientName,
		arg.RedirectUris,
		arg.GrantTypes,
		arg.ResponseTypes,
		arg.Scope,
		arg.LogoUrl,
	)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecret,
		&i.ClientName,
		&i.RedirectUris,
		&i.GrantTypes,
		&i.ResponseTypes,
		&i.Scope,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM oauth_clients
WHERE id = $1
`

func (q *Queries) DeleteClient(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteClient, id)
	return err
}

const getClientByClientID = `-- name: GetClientByClientID :one
SELECT id, client_id, client_secret, client_name, redirect_uris, grant_types, response_types, scope, logo_url, created_at, updated_at FROM oauth_clients
WHERE client_id = $1 LIMIT 1
`

func (q *Queries) GetClientByClientID(ctx context.Context, clientID string) (OauthClient, error) {
	row := q.db.QueryRow(ctx, getClientByClientID, clientID)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecret,
		&i.ClientName,
		&i.RedirectUris,
		&i.GrantTypes,
		&i.ResponseTypes,
		&i.Scope,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT id, client_id, client_secret, client_name, redirect_uris, grant_types, response_types, scope, logo_url, created_at, updated_at FROM oauth_clients
ORDER BY created_at DESC
`

func (q *Queries) ListClients(ctx context.Context) ([]OauthClient, error) {
	rows, err := q.db.Query(ctx, listClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OauthClient
	for rows.Next() {
		var i OauthClient
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientSecret,
			&i.ClientName,
			&i.RedirectUris,
			&i.GrantTypes,
			&i.ResponseTypes,
			&i.Scope,
			&i.LogoUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClient = `-- name: UpdateClient :one
UPDATE oauth_clients
SET 
    client_name = $2,
    redirect_uris = $3,
    grant_types = $4,
    response_types = $5,
    scope = $6,
    updated_at = NOW()
WHERE id = $1
RETURNING id, client_id, client_secret, client_name, redirect_uris, grant_types, response_types, scope, logo_url, created_at, updated_at
`

type UpdateClientParams struct {
	ID            pgtype.UUID `json:"id"`
	ClientName    string      `json:"client_name"`
	RedirectUris  []string    `json:"redirect_uris"`
	GrantTypes    []string    `json:"grant_types"`
	ResponseTypes []string    `json:"response_types"`
	Scope         string      `json:"scope"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (OauthClient, error) {
	row := q.db.QueryRow(ctx, updateClient,
		arg.ID,
		arg.ClientName,
		arg.RedirectUris,
		arg.GrantTypes,
		arg.ResponseTypes,
		arg.Scope,
	)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.ClientSecret,
		&i.ClientName,
		&i.RedirectUris,
		&i.GrantTypes,
		&i.ResponseTypes,
		&i.Scope,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
