// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthorizationCode struct {
	Code                string           `json:"code"`
	ClientID            pgtype.UUID      `json:"client_id"`
	UserID              pgtype.UUID      `json:"user_id"`
	RedirectUri         string           `json:"redirect_uri"`
	Scope               string           `json:"scope"`
	CodeChallenge       pgtype.Text      `json:"code_challenge"`
	CodeChallengeMethod pgtype.Text      `json:"code_challenge_method"`
	ExpiresAt           pgtype.Timestamp `json:"expires_at"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
}

type OauthClient struct {
	ID            pgtype.UUID      `json:"id"`
	ClientID      string           `json:"client_id"`
	ClientSecret  string           `json:"client_secret"`
	ClientName    string           `json:"client_name"`
	RedirectUris  []string         `json:"redirect_uris"`
	GrantTypes    []string         `json:"grant_types"`
	ResponseTypes []string         `json:"response_types"`
	Scopes        []string         `json:"scopes"`
	LogoUrl       string           `json:"logo_url"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type Token struct {
	ID                    pgtype.UUID      `json:"id"`
	AccessToken           string           `json:"access_token"`
	RefreshToken          pgtype.Text      `json:"refresh_token"`
	ClientID              pgtype.UUID      `json:"client_id"`
	UserID                pgtype.UUID      `json:"user_id"`
	Scope                 string           `json:"scope"`
	AccessTokenExpiresAt  pgtype.Timestamp `json:"access_token_expires_at"`
	RefreshTokenExpiresAt pgtype.Timestamp `json:"refresh_token_expires_at"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
}

type User struct {
	ID            pgtype.UUID      `json:"id"`
	Email         string           `json:"email"`
	PasswordHash  string           `json:"password_hash"`
	Name          string           `json:"name"`
	EmailVerified bool             `json:"email_verified"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}
