// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthorizationCode struct {
	Code                string           `json:"code"`
	ClientID            string           `json:"client_id"`
	UserID              pgtype.UUID      `json:"user_id"`
	RedirectUri         string           `json:"redirect_uri"`
	Scopes              []string         `json:"scopes"`
	Nonce               pgtype.Text      `json:"nonce"`
	CodeChallenge       pgtype.Text      `json:"code_challenge"`
	CodeChallengeMethod pgtype.Text      `json:"code_challenge_method"`
	Used                bool             `json:"used"`
	ExpiresAt           pgtype.Timestamp `json:"expires_at"`
	CreatedAt           pgtype.Timestamp `json:"created_at"`
}

type OauthClient struct {
	ID            pgtype.UUID      `json:"id"`
	ClientID      string           `json:"client_id"`
	ClientSecret  string           `json:"client_secret"`
	ClientName    string           `json:"client_name"`
	RedirectUris  []string         `json:"redirect_uris"`
	GrantTypes    []string         `json:"grant_types"`
	ResponseTypes []string         `json:"response_types"`
	Scopes        []string         `json:"scopes"`
	LogoUrl       string           `json:"logo_url"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

type Token struct {
	ID                    pgtype.UUID      `json:"id"`
	AccessTokenHash       string           `json:"access_token_hash"`
	RefreshTokenHash      string           `json:"refresh_token_hash"`
	AuthorizationCode     pgtype.Text      `json:"authorization_code"`
	ClientID              string           `json:"client_id"`
	UserID                pgtype.UUID      `json:"user_id"`
	Scopes                []string         `json:"scopes"`
	TokenType             string           `json:"token_type"`
	AccessTokenExpiresAt  pgtype.Timestamp `json:"access_token_expires_at"`
	RefreshTokenExpiresAt pgtype.Timestamp `json:"refresh_token_expires_at"`
	Revoked               bool             `json:"revoked"`
	RevokedAt             pgtype.Timestamp `json:"revoked_at"`
	RevokedReason         pgtype.Text      `json:"revoked_reason"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	LastUsedAt            pgtype.Timestamp `json:"last_used_at"`
}

type User struct {
	ID            pgtype.UUID      `json:"id"`
	Email         string           `json:"email"`
	PasswordHash  string           `json:"password_hash"`
	Name          string           `json:"name"`
	EmailVerified bool             `json:"email_verified"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}
