// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAuthorizationCode(ctx context.Context, arg CreateAuthorizationCodeParams) (AuthorizationCode, error)
	CreateClient(ctx context.Context, arg CreateClientParams) (OauthClient, error)
	DeleteAuthorizationCode(ctx context.Context, code string) error
	DeleteClient(ctx context.Context, id pgtype.UUID) error
	DeleteExpiredAuthorizationCodes(ctx context.Context) error
	GetAuthorizationCode(ctx context.Context, code string) (GetAuthorizationCodeRow, error)
	GetClientByClientID(ctx context.Context, clientID string) (OauthClient, error)
	ListClients(ctx context.Context) ([]OauthClient, error)
	UpdateClient(ctx context.Context, arg UpdateClientParams) (OauthClient, error)
}

var _ Querier = (*Queries)(nil)
