// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveTokensByClient = `-- name: CountActiveTokensByClient :one
SELECT COUNT(*) FROM tokens
WHERE client_id = $1
  AND revoked = FALSE
  AND access_token_expires_at > NOW()
`

func (q *Queries) CountActiveTokensByClient(ctx context.Context, clientID string) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveTokensByClient, clientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveTokensByUser = `-- name: CountActiveTokensByUser :one
SELECT COUNT(*) FROM tokens
WHERE user_id = $1
  AND revoked = FALSE
  AND access_token_expires_at > NOW()
`

func (q *Queries) CountActiveTokensByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveTokensByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createToken = `-- name: CreateToken :one
INSERT INTO tokens (
    id,
    access_token_hash,
    refresh_token_hash,
    authorization_code,
    client_id,
    user_id,
    scopes,
    token_type,
    access_token_expires_at,
    refresh_token_expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, access_token_hash, refresh_token_hash, authorization_code, client_id, user_id, scopes, token_type, access_token_expires_at, refresh_token_expires_at, revoked, revoked_at, revoked_reason, created_at, last_used_at
`

type CreateTokenParams struct {
	ID                    pgtype.UUID      `json:"id"`
	AccessTokenHash       string           `json:"access_token_hash"`
	RefreshTokenHash      string           `json:"refresh_token_hash"`
	AuthorizationCode     pgtype.Text      `json:"authorization_code"`
	ClientID              string           `json:"client_id"`
	UserID                pgtype.UUID      `json:"user_id"`
	Scopes                []string         `json:"scopes"`
	TokenType             string           `json:"token_type"`
	AccessTokenExpiresAt  pgtype.Timestamp `json:"access_token_expires_at"`
	RefreshTokenExpiresAt pgtype.Timestamp `json:"refresh_token_expires_at"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error) {
	row := q.db.QueryRow(ctx, createToken,
		arg.ID,
		arg.AccessTokenHash,
		arg.RefreshTokenHash,
		arg.AuthorizationCode,
		arg.ClientID,
		arg.UserID,
		arg.Scopes,
		arg.TokenType,
		arg.AccessTokenExpiresAt,
		arg.RefreshTokenExpiresAt,
	)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.AccessTokenHash,
		&i.RefreshTokenHash,
		&i.AuthorizationCode,
		&i.ClientID,
		&i.UserID,
		&i.Scopes,
		&i.TokenType,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.Revoked,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteExpiredTokens = `-- name: DeleteExpiredTokens :exec
DELETE FROM tokens
WHERE access_token_expires_at < NOW()
  AND refresh_token_expires_at < NOW()
`

func (q *Queries) DeleteExpiredTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredTokens)
	return err
}

const getActiveTokensByClient = `-- name: GetActiveTokensByClient :many
SELECT id, access_token_hash, refresh_token_hash, authorization_code, client_id, user_id, scopes, token_type, access_token_expires_at, refresh_token_expires_at, revoked, revoked_at, revoked_reason, created_at, last_used_at FROM tokens
WHERE client_id = $1
  AND revoked = FALSE
  AND access_token_expires_at > NOW()
ORDER BY created_at DESC
`

func (q *Queries) GetActiveTokensByClient(ctx context.Context, clientID string) ([]Token, error) {
	rows, err := q.db.Query(ctx, getActiveTokensByClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Token
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.AccessTokenHash,
			&i.RefreshTokenHash,
			&i.AuthorizationCode,
			&i.ClientID,
			&i.UserID,
			&i.Scopes,
			&i.TokenType,
			&i.AccessTokenExpiresAt,
			&i.RefreshTokenExpiresAt,
			&i.Revoked,
			&i.RevokedAt,
			&i.RevokedReason,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveTokensByUser = `-- name: GetActiveTokensByUser :many
SELECT id, access_token_hash, refresh_token_hash, authorization_code, client_id, user_id, scopes, token_type, access_token_expires_at, refresh_token_expires_at, revoked, revoked_at, revoked_reason, created_at, last_used_at FROM tokens
WHERE user_id = $1
  AND revoked = FALSE
  AND access_token_expires_at > NOW()
ORDER BY created_at DESC
`

func (q *Queries) GetActiveTokensByUser(ctx context.Context, userID pgtype.UUID) ([]Token, error) {
	rows, err := q.db.Query(ctx, getActiveTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Token
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.ID,
			&i.AccessTokenHash,
			&i.RefreshTokenHash,
			&i.AuthorizationCode,
			&i.ClientID,
			&i.UserID,
			&i.Scopes,
			&i.TokenType,
			&i.AccessTokenExpiresAt,
			&i.RefreshTokenExpiresAt,
			&i.Revoked,
			&i.RevokedAt,
			&i.RevokedReason,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTokenByAccessTokenHash = `-- name: GetTokenByAccessTokenHash :one
SELECT id, access_token_hash, refresh_token_hash, authorization_code, client_id, user_id, scopes, token_type, access_token_expires_at, refresh_token_expires_at, revoked, revoked_at, revoked_reason, created_at, last_used_at FROM tokens
WHERE access_token_hash = $1
  AND revoked = FALSE
LIMIT 1
`

func (q *Queries) GetTokenByAccessTokenHash(ctx context.Context, accessTokenHash string) (Token, error) {
	row := q.db.QueryRow(ctx, getTokenByAccessTokenHash, accessTokenHash)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.AccessTokenHash,
		&i.RefreshTokenHash,
		&i.AuthorizationCode,
		&i.ClientID,
		&i.UserID,
		&i.Scopes,
		&i.TokenType,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.Revoked,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getTokenByID = `-- name: GetTokenByID :one
SELECT id, access_token_hash, refresh_token_hash, authorization_code, client_id, user_id, scopes, token_type, access_token_expires_at, refresh_token_expires_at, revoked, revoked_at, revoked_reason, created_at, last_used_at FROM tokens
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTokenByID(ctx context.Context, id pgtype.UUID) (Token, error) {
	row := q.db.QueryRow(ctx, getTokenByID, id)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.AccessTokenHash,
		&i.RefreshTokenHash,
		&i.AuthorizationCode,
		&i.ClientID,
		&i.UserID,
		&i.Scopes,
		&i.TokenType,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.Revoked,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getTokenByRefreshTokenHash = `-- name: GetTokenByRefreshTokenHash :one
SELECT id, access_token_hash, refresh_token_hash, authorization_code, client_id, user_id, scopes, token_type, access_token_expires_at, refresh_token_expires_at, revoked, revoked_at, revoked_reason, created_at, last_used_at FROM tokens
WHERE refresh_token_hash = $1
  AND revoked = FALSE
  AND refresh_token_expires_at > NOW()
LIMIT 1
`

func (q *Queries) GetTokenByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (Token, error) {
	row := q.db.QueryRow(ctx, getTokenByRefreshTokenHash, refreshTokenHash)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.AccessTokenHash,
		&i.RefreshTokenHash,
		&i.AuthorizationCode,
		&i.ClientID,
		&i.UserID,
		&i.Scopes,
		&i.TokenType,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.Revoked,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getTokenWithDetails = `-- name: GetTokenWithDetails :one
SELECT
    t.id, t.access_token_hash, t.refresh_token_hash, t.authorization_code, t.client_id, t.user_id, t.scopes, t.token_type, t.access_token_expires_at, t.refresh_token_expires_at, t.revoked, t.revoked_at, t.revoked_reason, t.created_at, t.last_used_at,
    u.email as user_email,
    u.name as user_name,
    c.client_name as client_name
FROM tokens t
JOIN users u ON t.user_id = u.id
JOIN oauth_clients c ON t.client_id = c.client_id
WHERE t.id = $1
LIMIT 1
`

type GetTokenWithDetailsRow struct {
	ID                    pgtype.UUID      `json:"id"`
	AccessTokenHash       string           `json:"access_token_hash"`
	RefreshTokenHash      string           `json:"refresh_token_hash"`
	AuthorizationCode     pgtype.Text      `json:"authorization_code"`
	ClientID              string           `json:"client_id"`
	UserID                pgtype.UUID      `json:"user_id"`
	Scopes                []string         `json:"scopes"`
	TokenType             string           `json:"token_type"`
	AccessTokenExpiresAt  pgtype.Timestamp `json:"access_token_expires_at"`
	RefreshTokenExpiresAt pgtype.Timestamp `json:"refresh_token_expires_at"`
	Revoked               bool             `json:"revoked"`
	RevokedAt             pgtype.Timestamp `json:"revoked_at"`
	RevokedReason         pgtype.Text      `json:"revoked_reason"`
	CreatedAt             pgtype.Timestamp `json:"created_at"`
	LastUsedAt            pgtype.Timestamp `json:"last_used_at"`
	UserEmail             string           `json:"user_email"`
	UserName              string           `json:"user_name"`
	ClientName            string           `json:"client_name"`
}

func (q *Queries) GetTokenWithDetails(ctx context.Context, id pgtype.UUID) (GetTokenWithDetailsRow, error) {
	row := q.db.QueryRow(ctx, getTokenWithDetails, id)
	var i GetTokenWithDetailsRow
	err := row.Scan(
		&i.ID,
		&i.AccessTokenHash,
		&i.RefreshTokenHash,
		&i.AuthorizationCode,
		&i.ClientID,
		&i.UserID,
		&i.Scopes,
		&i.TokenType,
		&i.AccessTokenExpiresAt,
		&i.RefreshTokenExpiresAt,
		&i.Revoked,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.UserEmail,
		&i.UserName,
		&i.ClientName,
	)
	return i, err
}

const revokeToken = `-- name: RevokeToken :exec
UPDATE tokens
SET
    revoked = TRUE,
    revoked_at = NOW(),
    revoked_reason = $2
WHERE id = $1
`

type RevokeTokenParams struct {
	ID            pgtype.UUID `json:"id"`
	RevokedReason pgtype.Text `json:"revoked_reason"`
}

func (q *Queries) RevokeToken(ctx context.Context, arg RevokeTokenParams) error {
	_, err := q.db.Exec(ctx, revokeToken, arg.ID, arg.RevokedReason)
	return err
}

const revokeTokenByAccessTokenHash = `-- name: RevokeTokenByAccessTokenHash :exec
UPDATE tokens
SET
    revoked = TRUE,
    revoked_at = NOW(),
    revoked_reason = $2
WHERE access_token_hash = $1
`

type RevokeTokenByAccessTokenHashParams struct {
	AccessTokenHash string      `json:"access_token_hash"`
	RevokedReason   pgtype.Text `json:"revoked_reason"`
}

func (q *Queries) RevokeTokenByAccessTokenHash(ctx context.Context, arg RevokeTokenByAccessTokenHashParams) error {
	_, err := q.db.Exec(ctx, revokeTokenByAccessTokenHash, arg.AccessTokenHash, arg.RevokedReason)
	return err
}

const revokeTokensByAuthorizationCode = `-- name: RevokeTokensByAuthorizationCode :exec
UPDATE tokens
SET
    revoked = TRUE,
    revoked_at = NOW(),
    revoked_reason = $2
WHERE authorization_code = $1
  AND revoked = FALSE
`

type RevokeTokensByAuthorizationCodeParams struct {
	AuthorizationCode pgtype.Text `json:"authorization_code"`
	RevokedReason     pgtype.Text `json:"revoked_reason"`
}

func (q *Queries) RevokeTokensByAuthorizationCode(ctx context.Context, arg RevokeTokensByAuthorizationCodeParams) error {
	_, err := q.db.Exec(ctx, revokeTokensByAuthorizationCode, arg.AuthorizationCode, arg.RevokedReason)
	return err
}

const revokeTokensByClient = `-- name: RevokeTokensByClient :exec
UPDATE tokens
SET
    revoked = TRUE,
    revoked_at = NOW(),
    revoked_reason = $2
WHERE client_id = $1
  AND revoked = FALSE
`

type RevokeTokensByClientParams struct {
	ClientID      string      `json:"client_id"`
	RevokedReason pgtype.Text `json:"revoked_reason"`
}

func (q *Queries) RevokeTokensByClient(ctx context.Context, arg RevokeTokensByClientParams) error {
	_, err := q.db.Exec(ctx, revokeTokensByClient, arg.ClientID, arg.RevokedReason)
	return err
}

const revokeTokensByUser = `-- name: RevokeTokensByUser :exec
UPDATE tokens
SET
    revoked = TRUE,
    revoked_at = NOW(),
    revoked_reason = $2
WHERE user_id = $1
  AND revoked = FALSE
`

type RevokeTokensByUserParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	RevokedReason pgtype.Text `json:"revoked_reason"`
}

func (q *Queries) RevokeTokensByUser(ctx context.Context, arg RevokeTokensByUserParams) error {
	_, err := q.db.Exec(ctx, revokeTokensByUser, arg.UserID, arg.RevokedReason)
	return err
}

const updateLastUsedAt = `-- name: UpdateLastUsedAt :exec
UPDATE tokens
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateLastUsedAt(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateLastUsedAt, id)
	return err
}

const updateLastUsedAtByAccessTokenHash = `-- name: UpdateLastUsedAtByAccessTokenHash :exec
UPDATE tokens
SET last_used_at = NOW()
WHERE access_token_hash = $1
`

func (q *Queries) UpdateLastUsedAtByAccessTokenHash(ctx context.Context, accessTokenHash string) error {
	_, err := q.db.Exec(ctx, updateLastUsedAtByAccessTokenHash, accessTokenHash)
	return err
}
